algoritmo "calcula-media"

var
  peca,valor:real
  quantidade,codigo: inteiro

inicio

   escreval("Peças")
   escreval("Digite Código da peça")
   leia(codigo)


   escreval("Insira a quantidade de peças")
   leia(quantidade)
   
   escreval("Digite o valor da peça")
   leia(valor)
   

//calcula a media

          valor<- (quantidade*valor)

          escreval("Código: ",codigo,"valor ",valor)




fimalgoritmo
